raw_data_config: 
  raw_data_csv: data/raw/data.csv
  model_var: ['pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'grade_of_spondylolisthesis', 'target']
  train_test_split_ratio: 0.2
  target: target 
  random_state: 111
  new_train_data_csv: data/raw/train_new.csv
  file: data/column_3C.dat
  baseurl: 'https://archive.ics.uci.edu/ml/machine-learning-databases/00212/'

processed_data_config:
  train_data_csv: data/processed/vertebral_column_train.csv
  test_data_csv:  data/processed/vertebral_column_test.csv

model_choice:
  # random_forest or knn
  model: 'knn'
  # model: 'random_forest'

random_forest: 
  max_depth: 15
  n_estimators: 50

knn: 
  n_neighbors: 5

mlflow_global_config:
  artifacts_dir: artifacts
  experiment_name: model_vertebral_column
  registered_model_name: vertebral_column_model
  remote_server_uri: http://localhost:5000

mlflow_random_forest_config:
  run_name: random_forest
  

mlflow_knn_config:
  run_name: knn
  
model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
